### ISSUE TITLE
exposing publicly class "StackView" 

### ISSUE THREAD

**Issue by daviddoji** [European-XFEL/EXtra-data#78]
To make dictionaries compatible with the ```stack_detector_data``` API, one has to use the StackView class which is not publicly exposed by default.
As @takluyver has suggested, that class might be moved or changed in the future, so it would be nice to 
publicly available.

**Comment by takluyver** [comment]
To be precise, you can also put the data together in a regular numpy array - this is what `stack_detector_data` originally did, and still does by default. StackView was added in 0.7, so you can see the previous code in 0.6.2: https://github.com/European-XFEL/EXtra-data/blob/0.6.2/karabo_data/reader.py#L1263-L1341

StackView essentially pretends to be a numpy array - far enough for what EXtra-geom needs. It's nice because it avoids copying the separate module data together as a single array when you're about to copy them into different places to assemble an image anyway, so it can be faster.

Another option might be for EXtra-geom to accept something like a dict of `{modno: data}` as an alternative to an array. But maybe it's easiest just to make `StackView` public.

**Comment by daviddoji** [comment]
Both options works for me.
@takluyver any major reason for not making it public?

**Comment by takluyver** [comment]
Not really - I'm just in the habit of not making things public unless they need to be. More public API means more documentation, so it's harder for people to find the bit they want, and it limits what we can change in the future.
