### ISSUE TITLE
train_ids in KeyData

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/EXtra-data#91]
the `train_ids` attribute of the `KeyData` object is a simple copy of the train ids contained in the `DataCollection`. That leads to some inconsistencies. For example calling `.shape` will return a shape where the trainId axis match the actual count of data available in the files for the source, but calling `.train_ids` will contains train ids with and without data for this key.

One way to go around this if for example using xarray: `data.xarray().trainIds` will return only the train ids containing data, but that'd be ideal if it wasn't necessary to load the data to find which trainIds have or do not have data.

Would it be sensible to have the `train_ids` filtered (either at init or when the property is called) and only contains the train ids that actually have data for the key?

**Comment by takluyver** [comment]
I thought about this, but you have to access all the files in order to get that information - only the indexes, but even that can be slow. We've deliberately avoided doing that when you create a `KeyData` object so they're suitable for quick inspection. I think it's generally a bad design for properties to do significant work - `.shape` does in this case, but I don't want to proliferate that.

Maybe a decent compromise would be to expose the same functionality as `run.get_data_counts(source, key)` on KeyData objects.

**Comment by tmichela** [comment]
Yes, something like `get_data_counts` sound great
