### ISSUE TITLE
DAQ code design

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/EXtra-data#99]
Hi @tmichela, hi @takluyver,

I hope you are doing well and I am excited to post an issue here :-)

Actually, I have questions concerning how does the DAQ code write data incrementally into the file, which may not be related to EXtra-data, but very close:

1. In the run configurator, only the source names are pre-defined. So the code only knows the data type when it sees the data for the first time. Does it then allocate space for each property? i.e. create a dataset for each of them. Of course, it is well-known that the vector has a fixed length of 1000. Afterwards, I assume that the code makes an assumption that the data type and shape will not change on the fly. If this happens, it has two choices: ignore the illegal data or throw an exception, right?

2. Does the code write data into one file in a batch (i.e. first keep all the 500 trains in the memory, not sure whether it is possible) or one by one? For the last file, it normally does not have 500 trains. So does it first create a data set with 500 trains and then resize it? I noticed some file which has only 196 trains but the array length is 200. The rest are filled with 0.

Thanks a lot in advance!

Cheers,
Jun

**Comment by takluyver** [comment]
For Q2: I believe there is a configurable chunk size in the DAQ (not sure if it's configured through Karabo or elsewhere), for how much to extend the dataset each time it hits the end of the existing dataset. So in your file with 196 trains in an array of 200, the chunk size could be 5, 10 or 100. I think this may also be used as the HDF5 chunk size, but I'm not sure about that.

I'm going to hope that @tmichela knows more about Q1 than me - I'd have to look through a fair bit of Karabo code to attempt an answer.

**Comment by zhujun98** [comment]
Hi @takluyver Thanks for the answer for Q2. So you think a possible implementation could be first allocate a data set with 100 trains. If it hits the end then the data set is extended by another 100 trains until it reaches 500 and a new file will be created. This makes sense. I just wonder the potential overhead when extending a data set 5 times for each file, assuming the size of a  file with 500 trains is 20 GB.

This would be more like a brainstorming. Karabo is a good reference but maybe we could come up with a better design.

**Comment by tmichela** [comment]
Hi Jun,

regarding Q1:
Before acquiring data, the DAQ asks all monitored devices for their schema, in order to know what shape is expected for each sources and allocated this correctly in files. That is a common cause of failure in case the device sends data that do not match it's schema, for example having an additional data key that isn't present in the schema will lead to ignore all data or changing a camera ROI withour resetting the DAQ configuration will lead to misaligned data.
Note that for vectors, the default value is 1000, but this is configurable for each property at the device level, using the `maxSize` attribute.

> Does it then allocate space for each property?

Yes, and the data shape and size is extracted from the device schema (prior to receiving data)

> I assume that the code makes an assumption that the data type and shape will not change on the fly.

Yes, that's what the DAQ assumes, changing data properties while acquiring will lead to undefined behavior.

**Comment by tmichela** [comment]
>  If it hits the end then the data set is extended by another 100 trains until it reaches 500 and a new file will be created

Yes, that is how it works. And that's configured for each DataAggregators, meaning that the chunks can have different size for different files in the same run.

>  I just wonder the potential overhead when extending a data set 5 times for each file

It's probably negligible for large data (detectors), but not so much for 1d data. @takluyver has produced some bench marking for this in the past.

**Comment by zhujun98** [comment]
Hi Thomas,

> Before acquiring data, the DAQ asks all monitored devices for their schema, in order to know what shape is expected for each > sources and allocated this correctly in files.

OK. Schema makes life much easy here. 

I had this question since I am going to have my experiment and DOOCS offers the freedom of saving data as you like, which is also the only option for many experiments. I am thinking of creating a generalized solution as I have seen some "funny" code from users. Nevertheless, I cannot ask for the schema from DOOCS so I will have to come up with some "smart" solution :-(

**Comment by takluyver** [comment]
> So you think a possible implementation could be first allocate a data set with 100 trains. If it hits the end then the data set is extended by another 100 trains until it reaches 500 and a new file will be created.

Yup, that's what I believe is going on.

> I just wonder the potential overhead when extending a data set 5 times for each file, assuming the size of a file with 500 trains is 20 GB.

The actual point where you extend the dataset is relatively cheap, I think, because this should just be metadata. The new chunks are only allocated in the file when you write to them. But I think the HDF5 chunk size (which may be connected to this) could cause some overhead:

- If you have very small chunks (e.g. some indexes are written with each number in its own chunk), you create a lot of tiny chunks in the file, which means more small random access reads & writes rather than a few nice long reads.
- If your chunks are larger, and you are filling data into a chunk train by train, I *think* that means writing the whole of the chunk again each time. @tmichela do you know if the DAQ writes each train as it gets it, or buffers a chunk in memory to write in one go?

From what I understand, if there's a natural unit of reading or writing, e.g. one detector image, it makes sense for that to be a chunk. FWIW, if you create a chunked dataset with h5py and don't specify a chunk shape, it tries to guess a chunk between 8 KiB and 1 MiB in size.

**Comment by tmichela** [comment]
> do you know if the DAQ writes each train as it gets it, or buffers a chunk in memory to write in one go?

I don't know the answer to that.

**Comment by zhujun98** [comment]
> Yes, that is how it works. And that's configured for each DataAggregators, meaning that the chunks can have different size for different files in the same run.

I took a close look at some data:
- The pipeline data of XGM has a chunk size of (50, 1000) and its control data has a chunk size of (50,);
- The chunk size of JungFrau is (1, 1, 16, 512) with a full data shape of (500, 16, 512, 1024). But the chunk size of the scalar control data is also (50, ) and the vector control data is again (50, 1000).

In conclusion, 50 is the favorite number for chunk size in PC layer.

**Comment by zhujun98** [comment]
Thanks both @takluyver and @tmichela for the nice and inspiring discussion. Now, I have to get back to reality to write some working code.

**Comment by zhujun98** [comment]
> If your chunks are larger, and you are filling data into a chunk train by train, I think that means writing the whole of the chunk again each time

If I understood correctly, the chunk size used PC layer is small enough to fit the chunked data into the `raw chunk data cache`, which is 1MB by default. So the data will be first stored in the cache (memory) even if it writes the data train by train. The overhead maybe very small. As of 2.9 of `h5py`, one can also increase the `raw chunk data cache`. I am not sure when did the c library introduce it. Certainly the cache consumes memory, but it is normally not the bottle net of the XFEL cluster.

**Comment by takluyver** [comment]
I thought that the HDF5 chunk cache was only used in reading, but looking at the docs it seems I was wrong about that. They do talk about it being used for writing too. So I think you're right.

> As of 2.9 of h5py, one can also increase the raw chunk data cache. I am not sure when did the c library introduce it.

Ages ago - the docs say it was configurable [per file](https://portal.hdfgroup.org/display/HDF5/H5P_SET_CACHE) from before 1.6, and [per dataset](https://portal.hdfgroup.org/display/HDF5/H5P_SET_CHUNK_CACHE) since 1.8.3. So you can definitely use that ability.
